from . import blocked_domain_name
from . import custom_domain_name
from . import dns_domain
from . import dns_zone
from . import odoo_backup
from . import odoo_customer_plan
from . import odoo_instance_config
from . import odoo_instance_history
from . import odoo_instance_history_split
from . import odoo_instance_perm
from . import odoo_instance
from . import odoo_version_config
from . import odoo_vserver
from . import odoo_wallet
from . import product_product
from . import server_dns
from . import server_ip_line
from . import server_nginx
from . import server_odoo
from . import server_port
from . import server_postgresql
from . import server_server
