from . import blog_post
from . import forum_post
from . import ir_attachment
from . import res_users
from . import website_page
from . import abstract_joomla_model
from . import abstract_joomla_content
from . import abstract_joomla_migration_track
from . import joomla_article
from . import joomla_article_tag
from . import joomla_category
from . import joomla_menu
from . import joomla_tag
from . import joomla_user
from . import joomla_easyblog_meta
from . import joomla_easyblog_post
from . import joomla_easyblog_post_tag
from . import joomla_easyblog_tag
from . import joomla_easydiscuss_attachment
from . import joomla_easydiscuss_category
from . import joomla_easydiscuss_comment
from . import joomla_easydiscuss_post
from . import joomla_easydiscuss_post_tag
from . import joomla_easydiscuss_tag
from . import joomla_easydiscuss_vote
